### ISSUE TITLE
Request to Publish Quran_Module on PyPI

### ISSUE THREAD

**Issue by malekinho8** [UBISOFT-1/Quran_Module#2]
Salam,

I am the maintainer of the [fajrGPT](https://github.com/malekinho8/quran-wake-up) project, a Python application that aids in waking up for Fajr prayer while also helping people learn more about the Quran with ChatGPT. Your `Quran_Module` is a critical dependency for the project, and I'm truly grateful for your work on it.

I hope to publish `fajrGPT` on PyPI to simplify the installation process for users. However, PyPI requires all dependencies to be hosted on their platform. Currently, `Quran_Module` is not available on PyPI and must be installed directly from GitHub.

Would you consider publishing `Quran_Module` on PyPI? This would greatly assist us and potentially other projects that depend on your module.

Thank you for considering this request. We appreciate the valuable work you've done in creating and maintaining `Quran_Module`.

Best Regards,

Malek

**Comment by UBISOFT-1** [comment]
Hey @malekinho8 , I took a look at your project and it's amazing, really loved what you're doing. Sure let's publish this to PyPI. I will be doing just that in the new few hours, will keep you posted on the progress.

**Comment by UBISOFT-1** [comment]
Hey @malekinho8 I have gone ahead and uploaded `QuranModule` to PyPI. Since there was a similar repository, I've named it `TheQuranModule` :smile: you can go ahead and update `fajrGPT` accordingly. I would also like to offer my assistance on the project, namely on creating a UI and cross-platform executables for it. Though it is on an early stage I'd really love to see where we can take this, especially the GPT Powered Tafsir Feature.

**Comment by malekinho8** [comment]
Awesome, just tried it out and it works! Unfortunately there is still one dependency in my repo (youtube_dl) whose PyPI distribution still is not working for some reason, but everything else is working fine.

If you would be willing to help with the UI, I couldn't express my thanks enough, but of course no pressure. If Allah wills you to help, then I can only be grateful. 

Regarding the GPT Tafsir feature, I have been testing it and it still sometimes hallucinates answers, so I am having to do some prompt engineering unfortunately 😆 

Part of the problem is because the GPT 3.5 model is quite far behind GPT 4 in my experience with regards to Tafsir and recall of Quranic verses. When they make the GPT 4 API available, it will be pretty cool because I know GPT 4 is also very good at Arabic, and one idea I've had is to first obtain the Tafsir in Arabic, and then make another GPT call to translate the explanation into English. Given that GPT 4 has the potential to understand the Arabic language better than any human being hypothetically, I think this could open a door for more authentic or novel Tafsir. 

Anyways, I am going to be quite busy with school over the next several days, but any contributions you would make on the UI side would be much appreciated. Admittedly, that is an area I am still trying to learn more myself. The extent of my knowledge currently is CLI in Python. Thank you for your work!
