### ISSUE TITLE
PyPI Installation Issue

### ISSUE THREAD

**Issue by malekinho8** [UBISOFT-1/Quran_Module#5]
Hi @UBISOFT-1 ,

I hope you are doing well. I was just wanting to let you know that the PyPI installation package for this code is not up to date. I also noticed in the setup.py it is pointing to a Github branch on my end, but I think it should be pointing to the URL of the main branch (https://github.com/UBISOFT-1/Quran_Module). Just some minor issues that would help to make installation of my `fajrGPT` package a bit more streamlined! 

Best,
Malek

**Comment by UBISOFT-1** [comment]
Hi @malekinho8 sorry for the really late reply I actually don't use this account as often but I will add my other email here as well so I can get notifications whenever you update the source code. Can you provide me your PyPI username so I can give you access to the Quran-Module

**Comment by malekinho8** [comment]
No problem, my PyPI username is malekinho8

**Comment by UBISOFT-1** [comment]
@malekinho8 Updated. I'll add you as well. :)

**Comment by UBISOFT-1** [comment]
@malekinho8 See attached I've added you, you now need to accept invite.
![image](https://github.com/UBISOFT-1/Quran_Module/assets/54579186/5f3b1ea0-b53b-48a1-96c0-405fd65f190a)
