### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 57: character map s to <undefined>

### ISSUE THREAD

**Issue by devhindo** [UBISOFT-1/Quran_Module#7]
when running the sample code provided in the `README.md` file

**Comment by malekinho8** [comment]
Hey @devhindo , feel free to check out my fork [here](https://github.com/malekinho8/quran-module). You can also run

```
pip install git+https://github.com/malekinho8/quran-module -U
```

To upgrade your current installation if you are using pip, and it should fix the issue. It was just an encoding problem that isn't an issue with macOS (and Linux potentially), but it is a problem on Windows unfortunately. LMK if you run into any other troubles.

**Comment by UBISOFT-1** [comment]
@devhindo Sorry for the Late Reply, I have Updated the PyPI Index with the latest changes by @malekinho8 merged. @malekinho8 You can now also update `fajrGPT` documentation.
